project:
  type: website
  output-dir: docs


website:
  title: "Emissions Dashboard Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: data.qmd
        text: Data
      - href: model.qmd
        text: Model

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
